apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-cub
  annotations:
    kargo.akuity.io/color: purple
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-cub-warehouse
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-cub
  annotations:
    kargo.akuity.io/color: blue
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-cub-warehouse
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-cub
  annotations:
    kargo.akuity.io/color: green
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-cub-warehouse
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process