apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-cub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-cub
  template:
    metadata:
      labels:
        app: kargo-cub
    spec:
      containers:
      - name: nginx 
        image: public.ecr.aws/nginx/nginx:placeholder
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: content
        configMap:
          name: kargo-cub-content
